-- AlterTable
ALTER TABLE `Notification` MODIFY `type` ENUM('COUPON_REDEEMED', 'POINTS_PENDING', 'POINTS_CONFIRMED', 'POINTS_REJECTED', 'POINTS_ADJUSTED', 'BOOKING_CREATED', 'BOOKING_EDITED', 'BOOKING_CANCELLED', 'BOOKING_REMINDER') NOT NULL;
